### ISSUE TITLE
来自假的产品经理的需求

### ISSUE THREAD

**Issue by heymind** [cshunProjects/cshunTradeClient#10]
- [x] 新增登记完成后自动跳转到对应登记的订单编辑页面 https://github.com/cshunProjects/cshunTradeClient/pull/12/commits/9058b677e2ead52b942b1905495799542a15fa49
- [x] 在蔬果类登记中，以下栏目是应该出现必填标志的`生产主体，主题类型，主体负责人，主体负责人联系方式，品种，乡镇，所在村，种植面积，是否连片500亩以上，预计总产量，种植时间，预计上市时间，是否有冷链存储以及保本销售价格` e057c25 e5bbb45
- [x] 在畜牧类登记中，只有`销售负责人、销售负责人联系方式、二级品种`是非必填项目 e057c25 e5bbb45
- [x] 换一套配色显得改动比较大 e5bbb45 90a6098
- [x] 在获取`enrollments`中，使用`editable=1`获取有编辑权限的条目 8668a16
- [x] 国内订单地址信息应使用多级选择框而不是文本输入框 Assigned to @mister4tune c98f904

**Comment by Gaojianli** [comment]
> ![image](https://user-images.githubusercontent.com/11583541/47998066-f1720600-e138-11e8-9a89-3c1270539d30.png)
> 2.换套主题，看起来新一点，比如黑色变成绿色或者蓝色。

多级选择框的话需要从服务器获取地区数据
@heymind

**Comment by Gaojianli** [comment]
必填项目的显示自己尝试弄了一下，丑哭了。。。还是交给@Dixeran 来做吧

**Comment by heymind** [comment]
@Gaojianli 不用那么麻烦，label前加个＊号，底下写行小字，说加星时必填的即可

**Comment by Gaojianli** [comment]
@heymind 这个必填项需要校验么？

**Comment by heymind** [comment]
@Gaojianli 只要做了从服务端返回的字段错误处理就好，必填校验后端也做了
