### ISSUE TITLE
后端管理筛选与可视化需求

### ISSUE THREAD

**Issue by heymind** [cshunProjects/cshunTradeClient#37]
在种植类与养殖类后台管理界面中
- [x] 可根据所在村，街道，种类，以及上市时间范围作为筛选条件进行数据筛选（地区和种类是互斥筛选条件）
- [x] 可依据数据画出对应的饼状图 按照地区筛选就画种类占比饼状图，按照种类筛选就画地区占比饼状图

**Comment by Dixeran** [comment]
> 在种植类与养殖类后台管理界面中
指的是这两类的登记管理页面？第二个需求是否指的是“数据分析”下属的页面？还是在登记管理页面需要作图？

**Comment by FredericDT** [comment]
refs:
## filter
- https://front.id/en/articles/vuetify-achieve-multiple-filtering-data-table-component
- https://stackoverflow.com/questions/45672145/how-do-i-use-custom-filter-prop-in-data-tables-in-vuetify-or-how-do-i-create
- https://vuetifyjs.com/zh-Hans/components/data-tables
## echarts
- http://www.echartsjs.com/examples/editor.html?c=pie-roseType

**Comment by heymind** [comment]
- [ ] 二级品种直接忽视掉
- [ ] 按产地筛选若不选 社区字段 ，默认全选，要不什么也加载不出来了
