### ISSUE TITLE
PC 客户端需求

### ISSUE THREAD

**Issue by heymind** [cshunProjects/cshunTradeClient#39]
- [x] **兼容xp**
  - [x] js polyfill
  - [x] 改造nwjs
  - [x] 字体模糊问题
  - [x] icon 无法显示问题
- [x] 制作安装包
- [x] 修改产方登记布局以适应PC端

**Comment by Gaojianli** [comment]
你们加了nwjs不push的吗？

**Comment by heymind** [comment]
@Gaojianli nwjs不在这个仓里。。。只是改了一部分代码，然后似乎以及合不进master了，我彻底弄完再一次性解决冲突

**Comment by Dixeran** [comment]
仓库在？

**Comment by heymind** [comment]
@Dixeran 没仓库。。。如果有仓库里就是一堆dll和exe。。。就是个浏览器壳子，主要还是在前端做相关兼容性处理
