### ISSUE TITLE
修改登记表单

### ISSUE THREAD

**Issue by heymind** [cshunProjects/cshunTradeClient#4]
- [x] 主体类型可选，大户、合作社、企业
- [x] 乡镇、村选择器 ，字段 @heymind
- [x] 是否有冷链覆盖，使用radio
- [x] 是否连片500亩以上，radio
- [x] 增加销售联系人、销售负责人，非必填
- [x] 必填项校验

**Comment by heymind** [comment]
## 乡镇列表
GET /api/users/all_villages/
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

[
    null,
    "DSKJJFSDDFJK"
]

## 村列表
GET /api/users/all_streets/?village=DSKJJFSDDFJK
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

[
    "KsjkbFSD，JB,HACSHA"
]

**Comment by heymind** [comment]
add field `larger_than_500_acres` to planting enrollment model

**Comment by heymind** [comment]
every field in https://github.com/heymind/cshun_dock2_server/blob/master/enrollment/models.py without `blank=True` is required.

**Comment by Dixeran** [comment]
I'll try if I can fix it tonight.

**Comment by Gaojianli** [comment]
>           I'll try if I can fix it tonight.

please check the pr if it is compatible with the new backend
@Dixeran
